import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'src/styles/CapitalChallenge.module.css'
import CapitalMainWidget from 'src/components/CapitalMainWidget'

const Capital: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Capital Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <CapitalMainWidget />
      </div>
    </div>
  )
}

export default Capital
