import type { NextPage } from 'next'
import Head from 'next/head'
import CapitalMainWidget from 'src/components/CapitalMainWidget'

//TODO: replace by data in database
import Countries from 'src/dataMock/Countries';
import { OneCountry, newCountries } from 'src/dataMock/Countries';

const Capital: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Capital Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <CapitalMainWidget countries={newCountries} />
      </div>
    </div>
  )
}

export default Capital
