'use client';

import Head from 'next/head'
import CapitalMainWidget from 'src/components/CapitalMainWidget'

const CapitalChallenge = () => {
  return (
    <div>
      <Head>
        <title>Capital Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <CapitalMainWidget />
      </div>
    </div>
  )
}

export default CapitalChallenge
